/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface AppHello {
    }
    interface AppRoot {
    }
}
declare global {
    interface HTMLAppHelloElement extends Components.AppHello, HTMLStencilElement {
    }
    var HTMLAppHelloElement: {
        prototype: HTMLAppHelloElement;
        new (): HTMLAppHelloElement;
    };
    interface HTMLAppRootElement extends Components.AppRoot, HTMLStencilElement {
    }
    var HTMLAppRootElement: {
        prototype: HTMLAppRootElement;
        new (): HTMLAppRootElement;
    };
    interface HTMLElementTagNameMap {
        "app-hello": HTMLAppHelloElement;
        "app-root": HTMLAppRootElement;
    }
}
declare namespace LocalJSX {
    interface AppHello {
        "onHello"?: (event: CustomEvent<{ message: string }>) => void;
    }
    interface AppRoot {
    }
    interface IntrinsicElements {
        "app-hello": AppHello;
        "app-root": AppRoot;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "app-hello": LocalJSX.AppHello & JSXBase.HTMLAttributes<HTMLAppHelloElement>;
            "app-root": LocalJSX.AppRoot & JSXBase.HTMLAttributes<HTMLAppRootElement>;
        }
    }
}
